### ISSUE TITLE
Unable to open a model using T.mdl

### ISSUE THREAD

**Issue by RauliTop** [Solokiller/HL_Tools#97]
issue at latest beta version: 2.9 beta 002
Not present at 2.9 beta

When you try to open a model that uses a T.mdl, HLMV it's unable to open it.

Error message:
![errorhlmv](https://user-images.githubusercontent.com/13453517/80285612-7898ac80-8726-11ea-97c7-62bb30c608c3.png)

**Comment by Solokiller** [comment]
Can you provide the model files so i can test it locally?

**Comment by RauliTop** [comment]
> Can you provide the model files so i can test it locally?

You can download from here: http://gamer-lab.com/eng/mdl_goldsrc/RE4_Leon_Kennedi

**Comment by Solokiller** [comment]
It's opening for me.

Can you test if it opens correctly if there are no Unicode characters in the file path? It seems your Windows username has those in it. If it works without those then i'll have to rework the file loading code to support UTF8 in a better way.

**Comment by RauliTop** [comment]
> It's opening for me.
> 
> Can you test if it opens correctly if there are no Unicode characters in the file path? It seems your Windows username has those in it. If it works without those then i'll have to rework the file loading code to support UTF8 in a better way.

Yes, currently working outside that user path.

**Comment by Solokiller** [comment]
I've fixed the Unicode issues, try this build and see if it works: https://github.com/Solokiller/HL_Tools/releases/tag/V2.9-beta003

**Comment by RauliTop** [comment]
> I've fixed the Unicode issues, try this build and see if it works: https://github.com/Solokiller/HL_Tools/releases/tag/V2.9-beta003

Now is working fine.

Issue still remains happening with Load Next and Load Previous model function added at beta 002.

**Comment by Solokiller** [comment]
Alright that should be fixed as well now: https://github.com/Solokiller/HL_Tools/releases/tag/V2.9-beta003

**Comment by RauliTop** [comment]
Tested and fixed.

Issue close
